# -*- coding: utf-8 -*-
"""TEMA1_TIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5j09ss5llcTOcQdQErcRntc5yMRxvpC
"""

import os
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from skimage.io import imread
from skimage.transform import resize
import matplotlib.pyplot as plt
import pandas as pd

def load_dataset(root_folder):
    images = []
    labels = []
    class_mapping = {}
    for class_label, class_name in enumerate(os.listdir(root_folder)):
        class_mapping[class_label] = class_name
        class_folder = os.path.join(root_folder, class_name)
        for filename in os.listdir(class_folder):
            image_path = os.path.join(class_folder, filename)
            image = imread(image_path)
            if len(image.shape) == 3:
                # Redimensionăm imaginea la 64x64x3 și normalizăm pixelii
                image = resize(image, (64, 64, 3), anti_aliasing=True) / 255.0
            else:
                # Redimensionăm imaginea la 64x64 pentru imagini alb-negru și normalizăm
                image = resize(image, (64, 64), anti_aliasing=True) / 255.0
            images.append(image.flatten())  # Flatten transformă imaginea într-un vector
            labels.append(class_label)

    return np.array(images), np.array(labels), class_mapping

# Funcție pentru salvarea rezultatelor
def save_results(algorithm, y_true, y_pred, class_mapping):
    results_df = pd.DataFrame({'True Label':
                               [class_mapping[label] for label in y_true],
                               'Predicted Label':
                               [class_mapping[label] for label in y_pred]})

    results_folder = '/content/drive/MyDrive/TIA_TEMA1/result'
    if not os.path.exists(results_folder):
        os.makedirs(results_folder)
    results_file = os.path.join(results_folder, f'{algorithm}_results.csv')
    results_df.to_csv(results_file, index=False)
    print(f'Results saved for {algorithm} at {results_file}')

def plot_confusion_matrix(conf_matrix, class_mapping):
    plt.figure(figsize=(8, 6))
    plt.imshow(conf_matrix, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix')
    plt.colorbar()
    tick_marks = np.arange(len(class_mapping))
    plt.xticks(tick_marks, class_mapping.values(), rotation=45)
    plt.yticks(tick_marks, class_mapping.values())

    # Adăugarea valorilor numerice pe matrice
    thresh = conf_matrix.max() / 2.  # Prag pentru a schimba culoarea textului
    for i, j in np.ndindex(conf_matrix.shape):
        plt.text(j, i, format(conf_matrix[i, j], 'd'),
                 horizontalalignment="center",
                 color="white" if conf_matrix[i, j] > thresh else "black")

    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.show()

# Setul de date
dataset_folder = '/content/drive/MyDrive/TIA_TEMA1/dataset'  # Actualizați calea către folderul cu date
X, y, class_mapping = load_dataset(dataset_folder)

# Împărțirea în seturi de antrenare, validare și testare (60% antrenare, 20% validare, 20% testare)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Dimensiunile seturilor
print(f"Dimensiunea setului de antrenare: {len(X_train)} exemple")
print(f"Dimensiunea setului de validare: {len(X_val)} exemple")
print(f"Dimensiunea setului de testare: {len(X_test)} exemple")

# Proporții calculate
total_examples = len(X_train) + len(X_val) + len(X_test)
train_ratio = len(X_train) / total_examples
val_ratio = len(X_val) / total_examples
test_ratio = len(X_test) / total_examples

print(f"Proporția setului de antrenare: {train_ratio:.2%}")
print(f"Proporția setului de validare: {val_ratio:.2%}")
print(f"Proporția setului de testare: {test_ratio:.2%}")
# Verificare dimensiuni, se adauga totalul la 128 ceea ce e adevarat.

# Clasificator KNN
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_train, y_train)

# Antrenare
y_train_pred = knn_classifier.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Accuratețe pe setul de antrenare: {train_accuracy}")

train_conf_matrix = confusion_matrix(y_train, y_train_pred)
print("Matricea de confuzie pentru KNN pe setul de antrenare:\n", train_conf_matrix)

# Vizualizare matrice de confuzie pentru antrenare
plot_confusion_matrix(train_conf_matrix, class_mapping)

train_report = classification_report(y_train, y_train_pred, target_names=class_mapping.values())
print("Raport de clasificare pentru KNN pe setul de antrenare:\n", train_report)

# Validare
y_val_pred = knn_classifier.predict(X_val)
val_accuracy = accuracy_score(y_val, y_val_pred)
print(f"Accuratețe pe setul de validare: {val_accuracy}")

val_conf_matrix = confusion_matrix(y_val, y_val_pred)
print("Matricea de confuzie pentru KNN pe setul de validare:\n", val_conf_matrix)

# Vizualizare matrice de confuzie pentru validare
plot_confusion_matrix(val_conf_matrix, class_mapping)

val_report = classification_report(y_val, y_val_pred, target_names=class_mapping.values())
print("Raport de clasificare pentru KNN pe setul de validare:\n", val_report)

# Testare
y_test_pred_knn = knn_classifier.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred_knn)
print(f"Accuratețe pe setul de testare: {test_accuracy}")

test_conf_matrix = confusion_matrix(y_test, y_test_pred_knn)
print("Matricea de confuzie pentru KNN pe setul de testare:\n", test_conf_matrix)

# Vizualizare matrice de confuzie pentru testare
plot_confusion_matrix(test_conf_matrix, class_mapping)

test_report = classification_report(y_test, y_test_pred_knn, target_names=class_mapping.values())
print("Raport de clasificare pentru KNN pe setul de testare:\n", test_report)

# Salvarea rezultatelor pentru testare
save_results('knn', y_test, y_test_pred_knn, class_mapping)

from sklearn.naive_bayes import GaussianNB

# Clasificator Naive Bayes
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

# Antrenare Naive Bayes
y_train_pred_nb = nb_classifier.predict(X_train)
train_accuracy_nb = accuracy_score(y_train, y_train_pred_nb)
print(f"Accuratețe pe setul de antrenare (Naive Bayes): {train_accuracy_nb}")

train_conf_matrix_nb = confusion_matrix(y_train, y_train_pred_nb)
print("Matricea de confuzie pentru Naive Bayes pe setul de antrenare:\n", train_conf_matrix_nb)

plot_confusion_matrix(train_conf_matrix_nb, class_mapping)

train_report_nb = classification_report(y_train, y_train_pred_nb, target_names=class_mapping.values())
print("Raport de clasificare pentru Naive Bayes pe setul de antrenare:\n", train_report_nb)

# Validare Naive Bayes
y_val_pred_nb = nb_classifier.predict(X_val)
val_accuracy_nb = accuracy_score(y_val, y_val_pred_nb)
print(f"Accuratețe pe setul de validare (Naive Bayes): {val_accuracy_nb}")

val_conf_matrix_nb = confusion_matrix(y_val, y_val_pred_nb)
print("Matricea de confuzie pentru Naive Bayes pe setul de validare:\n", val_conf_matrix_nb)

plot_confusion_matrix(val_conf_matrix_nb, class_mapping)

val_report_nb = classification_report(y_val, y_val_pred_nb, target_names=class_mapping.values())
print("Raport de clasificare pentru Naive Bayes pe setul de validare:\n", val_report_nb)

# Testare Naive Bayes
y_test_pred_nb = nb_classifier.predict(X_test)
test_accuracy_nb = accuracy_score(y_test, y_test_pred_nb)
print(f"Accuratețe pe setul de testare (Naive Bayes): {test_accuracy_nb}")

test_conf_matrix_nb = confusion_matrix(y_test, y_test_pred_nb)
print("Matricea de confuzie pentru Naive Bayes pe setul de testare:\n", test_conf_matrix_nb)

plot_confusion_matrix(test_conf_matrix_nb, class_mapping)

test_report_nb = classification_report(y_test, y_test_pred_nb, target_names=class_mapping.values())
print("Raport de clasificare pentru Naive Bayes pe setul de testare:\n", test_report_nb)

# Salvarea rezultatelor pentru Naive Bayes
save_results('naive_bayes', y_test, y_test_pred_nb, class_mapping)

# Compararea rezultatelor KNN vs. Naive Bayes
print(f"\nCompararea performanțelor între KNN și Naive Bayes pe setul de testare:")
print(f"Accuratețe KNN: {test_accuracy}")
print(f"Accuratețe Naive Bayes: {test_accuracy_nb}")